# Generated by Django 4.2.5 on 2023-09-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='status',
            field=models.CharField(default='None', max_length=122),
            preserve_default=False,
        ),
    ]
