# Generated by Django 4.2.5 on 2023-09-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_transactions_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='id',
        ),
        migrations.AddField(
            model_name='transactions',
            name='transaction_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transactions',
            name='status',
            field=models.CharField(default='None', max_length=122),
        ),
    ]
