# Generated by Django 4.2.5 on 2023-09-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_transactions_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='payment_id',
            field=models.CharField(max_length=122),
        ),
    ]
